version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/teste.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output src/teste.csproj
artifacts:
  files:
    - dotnetLexChatBot/build_output/**/*
    - scripts/**/*
    - appspec.yml
